import { COUNTRY_BY_ID, medianWage } from './countries.js';
import { makeRng } from './rng.js';
import { openCriminalCase } from './judicial.js';

export const MODES=[['walk','Walking'],['bicycle','Bicycle'],['motorcycle','Motorcycle or scooter'],['transit','Public transportation'],['taxi','Taxi or ride-hailing'],['family_car','Family vehicle'],['car','Personal vehicle']];
export const VEHICLES={used_car:{label:'Used car',price:1.2,fuel:'petrol',reliability:.72},new_car:{label:'New car',price:3.2,fuel:'petrol',reliability:.94},motorcycle:{label:'Motorcycle or scooter',price:.55,fuel:'petrol',reliability:.82},electric_car:{label:'Electric car',price:3.8,fuel:'electricity',reliability:.95}};
const EU_ID=new Set(['Austria','Belgium','Bulgaria','Croatia','Cyprus','Czechia','Denmark','Estonia','Finland','France','Germany','Greece','Hungary','Iceland','Ireland','Italy','Latvia','Liechtenstein','Lithuania','Luxembourg','Malta','Netherlands','Norway','Poland','Portugal','Romania','Slovakia','Slovenia','Spain','Sweden','Switzerland']);
const SOUTH_AMERICAN_ID=new Set(['Argentina','Bolivia','Brazil','Chile','Colombia','Ecuador','Paraguay','Peru','Uruguay']);
function localRng(ch,salt){let h=2166136261;for(const c of `${ch.identity?.birthName||ch.countryId}|${ch.age}|${salt}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return makeRng(h>>>0);}
export function transportProfile(country){return{licenseAge:['United States','Canada'].includes(country.name)?16:['Australia','New Zealand','United Kingdom'].includes(country.name)?17:18,transit:country.urbanization>=65&&country.incomeTier>=3?'extensive':country.urbanization>=45?'limited':'minimal',insuranceRequired:country.incomeTier>=2||country.lawTier==='strong',fuelPriceIndex:Math.max(.55,1.35-(country.gdpPerCapita||10000)/100000),electricityIndex:Math.max(.45,1.15-(country.incomeTier||2)*.1),roadRisk:Math.max(.55,1.65-(country.incomeTier||2)*.22+(country.lawTier==='weak'?.22:0))};}
export function initTransportation(ch){return{primaryMode:ch.age<16?'walk':'transit',backupMode:'walk',license:{status:'none',years:0,points:0,suspendedYears:0,commercial:false},vehicle:null,insurance:{coverage:'none',claims:0,premium:0},safetyPolicy:'never',annualKm:0,drivingRecord:[],utilities:{electricity:'normal',water:'normal',heating:'normal',internet:true,lastYear:{},arrears:0,disconnected:false,outageYears:0},documents:{passports:[],nationalIds:[],pending:null,lostHistory:[]}};}
export function ensureTransportation(ch){ch.transportation||=initTransportation(ch);const t=ch.transportation;t.license||=initTransportation(ch).license;t.insurance||=initTransportation(ch).insurance;t.utilities||=initTransportation(ch).utilities;t.documents||=initTransportation(ch).documents;t.drivingRecord||=[];return t;}
export function modeAvailability(ch,country){const t=ensureTransportation(ch),profile=transportProfile(country),familyVehicle=(ch.spouse?.alive||(ch.family||[]).some(x=>x.alive&&['Mother','Father'].includes(x.relation)))&&ch.age>=16;return{
  walk:{available:true,reason:'Available'},bicycle:{available:country.urbanization>=25,reason:'Requires usable local roads'},
  motorcycle:{available:t.vehicle?.type==='motorcycle',reason:'Requires an owned motorcycle or scooter'},
  transit:{available:profile.transit!=='minimal'||country.urbanization>=30,reason:'Depends on local public transportation'},taxi:{available:country.urbanization>=35,reason:'Depends on local taxi or ride-hailing service'},
  family_car:{available:familyVehicle,reason:'Requires access to a household vehicle'},car:{available:!!t.vehicle&&t.vehicle.type!=='motorcycle',reason:'Requires an owned personal car'},
};}
export function setTransportMode(ch,country,primary,backup){const t=ensureTransportation(ch),availability=modeAvailability(ch,country);if(!availability[primary]?.available||!availability[backup]?.available)return false;t.primaryMode=primary;t.backupMode=backup;return true;}
export function applyDrivingLicense(ch,country,commercial=false){const t=ensureTransportation(ch),p=transportProfile(country);if(ch.age<p.licenseAge)return false;if(t.license.status==='conversion_required'){const cost=medianWage(country)*.025;if(ch.money.bank<cost)return false;ch.money.bank-=cost;t.license.status='licensed';return true;}if(commercial&&t.license.status==='licensed'&&!t.license.commercial){const cost=medianWage(country)*.08;if((ch.money.bank||0)<cost)return false;ch.money.bank-=cost;t.license.commercial=true;return true;}if(t.license.status!=='none')return false;const cost=medianWage(country)*.035;if((ch.money.bank||0)<cost)return false;ch.money.bank-=cost;t.license.status='licensed';return true;}
export function buyVehicle(ch,country,type,finance=false){const t=ensureTransportation(ch),v=VEHICLES[type];if(ch.age<18||!v||t.vehicle)return false;const price=medianWage(country)*v.price,down=finance?price*.2:price;if(ch.money.bank<down)return false;ch.money.bank-=down;if(finance){ch.debts.vehicle=(ch.debts.vehicle||0)+price-down;}t.vehicle={type,label:v.label,value:price,fuel:v.fuel,reliability:v.reliability,age:0,financed:finance};t.primaryMode=type==='motorcycle'?'motorcycle':'car';return true;}
export function sellVehicle(ch){const t=ensureTransportation(ch);if(!t.vehicle)return false;const proceeds=t.vehicle.value*.88,debt=ch.debts.vehicle||0,pay=Math.min(debt,proceeds);ch.debts.vehicle=debt-pay;ch.money.bank+=proceeds-pay;t.vehicle=null;t.primaryMode='transit';return true;}
export function setVehicleInsurance(ch,country,coverage){const t=ensureTransportation(ch);if(!['none','third_party','comprehensive'].includes(coverage)||!t.vehicle)return false;if(coverage==='none'&&transportProfile(country).insuranceRequired)return false;t.insurance.coverage=coverage;return true;}
export function setDrivingSafety(ch,value){if(!['never','sometimes','frequent'].includes(value))return false;ensureTransportation(ch).safetyPolicy=value;return true;}
export function setUtilityUse(ch,key,value){const t=ensureTransportation(ch);if(!['electricity','water','heating'].includes(key)||!['reduced','normal','high'].includes(value))return false;t.utilities[key]=value;return true;}

export function passportRequirement(ch,target,route){const t=ensureTransportation(ch),citizenships=ch.immigration?.citizenships||[ch.countryId],valid=t.documents.passports.some(p=>citizenships.includes(p.countryId)&&p.expiresAge>ch.age),idCountries=t.documents.nationalIds.filter(x=>citizenships.includes(x.countryId)&&x.expiresAge>ch.age).map(x=>COUNTRY_BY_ID[x.countryId]?.name),regionalId=idCountries.some(name=>(EU_ID.has(name)&&EU_ID.has(target.name))||(SOUTH_AMERICAN_ID.has(name)&&SOUTH_AMERICAN_ID.has(target.name)));if(['irregular','asylum','deportation'].includes(route))return{ok:true,document:'exception'};return valid||regionalId?{ok:true,document:regionalId?'national identity card':'passport'}:{ok:false,reason:'A valid passport or accepted regional identity card is required before travel.'};}
export function applyPassport(ch,country,citizenshipId=country.id){const t=ensureTransportation(ch),legal=ch.judicial;if(ch.age<16||!ch.immigration?.citizenships?.includes(citizenshipId)||t.documents.pending||legal?.warrant||legal?.activeCase?.kind==='criminal'||legal?.investigation?.exitRestricted)return false;const cost=medianWage(country)*.025;if(ch.money.bank<cost)return false;ch.money.bank-=cost;t.documents.pending={countryId:citizenshipId,yearsRemaining:1,type:'passport'};return true;}
export function applyNationalId(ch,country,citizenshipId=country.id){const t=ensureTransportation(ch);if(ch.age<12||!ch.immigration?.citizenships?.includes(citizenshipId)||t.documents.pending)return false;const cost=medianWage(country)*.006;if(ch.money.bank<cost)return false;ch.money.bank-=cost;t.documents.pending={countryId:citizenshipId,yearsRemaining:1,type:'nationalId'};return true;}

function householdSize(ch){return 1+(ch.spouse?.alive?1:0)+(ch.family||[]).filter(x=>x.relation==='Child'&&x.alive&&x.atHome!==false).length;}
export function utilityEstimate(ch,country){const t=ensureTransportation(ch),mw=medianWage(country),size=householdSize(ch),mult=v=>({reduced:.72,normal:1,high:1.38}[v]||1),owner=ch.ownsHome?1.15:1,ev=t.vehicle?.fuel==='electricity'?mw*.025:0;return{electricity:mw*.035*size**.45*mult(t.utilities.electricity)*owner+ev,water:mw*.018*size**.55*mult(t.utilities.water),heating:mw*.025*size**.4*mult(t.utilities.heating)*owner,internet:t.utilities.internet?mw*.018:0};}

export function resolveTransportationYear(ch,country){const t=ensureTransportation(ch),rng=localRng(ch,'transport'),p=transportProfile(country),expenses=[],logs=[];
  if(t.documents.pending){t.documents.pending.yearsRemaining--;if(t.documents.pending.yearsRemaining<=0){const d=t.documents.pending,tgt=d.type==='passport'?t.documents.passports:t.documents.nationalIds;tgt.push({countryId:d.countryId,issuedAge:ch.age,expiresAge:ch.age+(d.type==='passport'?10:8)});logs.push(`Your ${d.type==='passport'?'passport':'national identity card'} was issued.`);t.documents.pending=null;}}
  for(const list of [t.documents.passports,t.documents.nationalIds])for(const d of list)if(d.expiresAge===ch.age)logs.push(`Your ${list===t.documents.passports?'passport':'national identity card'} expired.`);
  const validPassport=t.documents.passports.find(x=>x.expiresAge>ch.age);if(validPassport&&rng.chance(.003)){t.documents.passports=t.documents.passports.filter(x=>x!==validPassport);t.documents.lostHistory.push({...validPassport,lostAge:ch.age});logs.push('Your passport was lost or stolen and must be replaced before most international travel.');}
  const util=utilityEstimate(ch,country);t.utilities.lastYear=util;for(const [key,amount] of Object.entries(util))if(amount>0)expenses.push({label:`Utilities — ${key[0].toUpperCase()+key.slice(1)}`,amount,household:true,utility:true});
  if(country.incomeTier<=2&&rng.chance(country.incomeTier===1?.14:.06)){t.utilities.outageYears++;logs.push('Electricity or water service was interrupted by unreliable local infrastructure.');}
  if(ch.lastStatement?.hardship){t.utilities.arrears+=Object.values(util).reduce((s,x)=>s+x,0)*.35;if(rng.chance(country.lawTier==='strong'?.08:.18)){t.utilities.disconnected=true;logs.push('Utility arrears caused a temporary service disconnection.');}}
  else if(t.utilities.arrears>0){const payment=Math.min(t.utilities.arrears,medianWage(country)*.05);t.utilities.arrears-=payment;expenses.push({label:'Utility arrears payment',amount:payment,household:true,utility:true});if(t.utilities.disconnected&&t.utilities.arrears<1){t.utilities.disconnected=false;logs.push('Household utility service was restored after the arrears were paid.');}}
  const available=modeAvailability(ch,country);if(!available[t.primaryMode]?.available){t.primaryMode=available[t.backupMode]?.available?t.backupMode:'walk';logs.push('Your usual transportation was unavailable, so you used an available alternative.');}
  const mode=t.primaryMode,drives=['car','family_car','motorcycle'].includes(mode)&&t.license.status==='licensed'&&t.license.suspendedYears<=0;t.annualKm=drives?(ch.job&&['transport_local','transport_heavy'].includes(ch.job.sector)?32000:9000):0;
  if(t.license.status==='licensed')t.license.years++;if(t.license.suspendedYears>0){t.license.suspendedYears--;if(!t.license.suspendedYears)t.license.status='licensed';}
  if(t.vehicle){const v=VEHICLES[t.vehicle.type],fuel=t.annualKm/100*(t.vehicle.type==='motorcycle'?3.5:t.vehicle.type==='electric_car'?18:8)*medianWage(country)*(v.fuel==='electricity'?.000018*p.electricityIndex:.000055*p.fuelPriceIndex);expenses.push({label:v.fuel==='electricity'?'Vehicle electricity':'Vehicle fuel',amount:fuel,household:true});const maintenance=t.vehicle.value*(.025+(1-t.vehicle.reliability)*.08);expenses.push({label:'Vehicle maintenance and registration',amount:maintenance,household:true});t.vehicle.age++;t.vehicle.value*=.86;t.vehicle.reliability=Math.max(.35,t.vehicle.reliability-.025);
    if((ch.debts.vehicle||0)>0){const balance=ch.debts.vehicle*1.07,payment=Math.min(balance,Math.max(medianWage(country)*.12,balance/5));ch.debts.vehicle=balance-payment;expenses.push({label:'Vehicle loan payment',amount:payment,household:true});}
    const basePremium=t.vehicle.value*(t.insurance.coverage==='comprehensive'?.09:t.insurance.coverage==='third_party'?.04:0),experience=Math.max(.7,1.35-t.license.years*.04),record=1+t.insurance.claims*.25+t.license.points*.04;t.insurance.premium=basePremium*experience*record;if(t.insurance.premium)expenses.push({label:`Vehicle insurance — ${t.insurance.coverage.replace('_',' ')}`,amount:t.insurance.premium,household:true});
    if(p.insuranceRequired&&t.insurance.coverage==='none'&&rng.chance(.08)&&!ch.judicial?.activeCase){openCriminalCase(ch,country,'uninsured_driving',{guilty:true,source:'traffic enforcement'});logs.push('Driving without required insurance led to a charge.');}
  }
  if(drives){const impaired=t.safetyPolicy==='frequent'?.14:t.safetyPolicy==='sometimes'?.045:0,substance=(ch.lifeState?.measurements?.drinksWeek||0)>=7||Object.values(ch.adultLife?.substances||{}).some(x=>['frequent','dependent'].includes(x));if(substance&&rng.chance(impaired)&&!ch.judicial?.activeCase){openCriminalCase(ch,country,'dui',{guilty:true,source:'traffic enforcement'});t.license.points+=6;t.license.status='suspended';t.license.suspendedYears=1;t.drivingRecord.push({age:ch.age,type:'DUI'});logs.push('You were charged with impaired driving and your licence was suspended.');}
    if(rng.chance(.025*p.roadRisk*Math.max(.65,1.25-t.license.years*.035))){const serious=rng.chance(mode==='motorcycle'?.28:.1);t.drivingRecord.push({age:ch.age,type:serious?'serious crash':'crash'});t.insurance.claims++;t.license.points+=serious?4:1;const damage=(t.vehicle?.value||medianWage(country))*(serious?.35:.12),covered=t.insurance.coverage==='comprehensive';expenses.push({label:'Vehicle crash damage',amount:covered?damage*.2:damage,household:true});if(serious){ch.health.lastSevereEvent={age:ch.age,name:'Road traffic injury',mortalityRisk:.08,treated:true};logs.push('A road crash caused a serious injury and an insurance claim.');}else logs.push('A road crash caused vehicle damage and an insurance claim.');}}
  if(!drives&&['walk','bicycle','motorcycle','transit'].includes(mode)){const risk={walk:.002,bicycle:.004,motorcycle:.018,transit:.0005}[mode]*p.roadRisk;if(rng.chance(risk)){const severe=rng.chance(mode==='motorcycle'?.28:.08);expenses.push({label:'Transportation injury treatment',amount:medianWage(country)*(severe?.16:.025)});t.drivingRecord.push({age:ch.age,type:`${mode} transport injury`});if(severe)ch.health.lastSevereEvent={age:ch.age,name:'Road traffic injury',mortalityRisk:.05,treated:true};logs.push(`A ${mode.replace('_',' ')} transportation incident caused ${severe?'a serious':'a minor'} injury.`);}}
  return{expenses,logs};}
